# Generated by Django 3.0.7 on 2021-03-20 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210320_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time',
            old_name='Time',
            new_name='time',
        ),
    ]
