# Generated by Django 3.1 on 2021-03-20 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('file', models.FileField(blank=True, default='', null=True, upload_to='file/')),
                ('Subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.subject')),
                ('resource_by', models.ForeignKey(limit_choices_to={'is_student': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('due_at', models.DateTimeField()),
                ('Subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.subject')),
                ('reminder_by', models.ForeignKey(limit_choices_to={'is_student': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
